apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-greeting-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greeting-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-greeting-app
    spec:
      containers:
      - name: {{ .Release.Name }}-greeting-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-greeting-config
              key: GREETING
        - name: SECRET_RECIPE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-recipe-secrets
              key: secret-recipe
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
