apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-greeting-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-greeting-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 3000
