replicaCount: 3

image:
  repository: my-greeting-app
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"

config:
  greetingMessage: "Hello K8s!"
