apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-app # This should match the label in your deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will expose
      targetPort: 3000 # The port the container listens on
  type: NodePort # This exposes the service on each Node’s IP at a static port
